<?php
/**
 * Chimera PHP Configuration
 * Generated by the installer. Edit manually if needed.
 */
return [
    // Cloudflare Workers AI credentials
    'cf_account_id' => '',
    'cf_api_token' => '',

    // LLM Model
    'model' => '@cf/ibm-granite/granite-4.0-h-micro',

    // System prompt (who is your agent?)
    'system_prompt' => 'You are a helpful AI assistant with access to tools for file operations, shell commands, and memory. Be concise and direct.',

    // Agent name
    'agent_name' => 'Chimera',

    // Data directory (relative to this file)
    'data_dir' => __DIR__ . '/data',

    // Max iterations per request (prevent runaway)
    'max_iterations' => 15,

    // Security: allowed origins for CORS (comma-separated, or * for all)
    'cors_origin' => '*',

    // Security: API key for the HTTP API (leave empty for no auth)
    'api_key' => '',

    // Memory dimensions (768 for EmbeddingGemma-300m)
    'dimensions' => 768,

    // Enable tools (disable what you don't need)
    'enable_memory' => true,
    'enable_shell' => false,  // Disabled by default on shared hosting for security
    'enable_a2e' => true,
];
